### ISSUE TITLE
Please tag your release

### ISSUE THREAD

**Issue by dod38fr** [azawawi/raku-file-which#13]
Hello

In Debian, we have a toolset (i.e. [uscan](https://manpages.debian.org/unstable/devscripts/uscan.1.en.html)) to track upstream release that work on GitHub tags.

Without release tags, the tracking tools are not working and we are not aware when a new release is mage. Which means Debian packages will lag behind your releases.

So please tag at least the last release and any future release.

All the best

Dod (for Debian)

**Comment by azawawi** [comment]
It is now tagged. Sorry for the delay on this one 👍
