### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by azawawi** [azawawi/raku-file-which#24]
@sdondley Hi. There are windows test failures in https://github.com/azawawi/raku-file-which/blob/master/t/04-simple.rakutest#L10 and https://github.com/azawawi/raku-file-which/blob/master/t/04-simple.rakutest#L31. Can you please take a look at them?

**Comment by azawawi** [comment]
@ugexe This one is failing silently https://github.com/azawawi/raku-file-which/commit/83eef687831ec9143ca9b7e5b11ec1b8f71fb23e#diff-c0603408fbb82775643ce12ba9530491f1e9742286f47fa4e25dac7b34d95d57R8. If we revert it to `use Win32::Registry`, tests start passing again on windows.

**Comment by ugexe** [comment]
It wasn't failing on the appveyor build when it existed though

**Comment by azawawi** [comment]
The error message when I remove the `try` is the following:
`# Trying to import from 'Win32::Registry', but the following symbols are missing: AssocQueryStringA, RegGetValueW, key-exists, open-key, close-key, wstr`

**Comment by azawawi** [comment]
@ugexe Hmmm AssocQueryStringA is already redefined in File::Which and when we use compile-time, it works

```diff
-try require Win32::Registry qw<AssocQueryStringA RegGetValueW key-exists open-key close-key wstr>;
+try require Win32::Registry qw<&RegGetValueW &key-exists &open-key &close-key &wstr>;
```

**Comment by ugexe** [comment]
Yeah I see the correct behavior after that change as well. I'm still baffled by why it didn't fail CI when I opened my PR though...

**Comment by azawawi** [comment]
> Yeah I see the correct behavior after that change as well. I'm still baffled by why it didn't fail CI when I opened my PR though...

FYI. The old appveyor CI was not working as expected.

It is now passing on all platforms again.
https://github.com/azawawi/raku-file-which/actions/runs/3315996017

**Comment by azawawi** [comment]
Fixed in https://github.com/azawawi/raku-file-which/commit/893d726776bdec73648739627998c454ed63f886. Bumped to 1.0.4.

@ugexe Thanks 👍
